### ISSUE TITLE
Jplag throws exception if there is no comparison above -m value

### ISSUE THREAD

**Issue by Christina96** [jplag/JPlag#1018]
To be more precise: I had a project with java files and the comparison results for these were 0.0. But I had as configuration -m 0.01 and jplag throw the error below:

Exception in thread "main" org.apache.commons.math3.exception.NotStrictlyPositiveException: 0 is smaller than, or equal to, the minimum (0)
        at org.apache.commons.math3.linear.AbstractRealMatrix.<init>(AbstractRealMatrix.java:68)
        at org.apache.commons.math3.linear.Array2DRowRealMatrix.<init>(Array2DRowRealMatrix.java:60)
        at de.jplag.clustering.ClusteringAdapter.<init>(ClusteringAdapter.java:41)
        at de.jplag.clustering.ClusteringFactory.getClusterings(ClusteringFactory.java:53)
        at de.jplag.JPlag.run(JPlag.java:67)
        at de.jplag.cli.CLI.main(CLI.java:91)

**Comment by tsaglam** [comment]
Addressed by #1070.
