### ISSUE TITLE
Enhancement: print the file name if parse failed

### ISSUE THREAD

**Issue by hnwyllmm** [jplag/JPlag#1386]
I use JPlag for checking [miniob](https://github.com/oceanbase/miniob) which use C++ 20 not supported by JPlag. So there are some exceptions when parsing the code.

I have two suggestions.
1. Print the file name if except occurs;
2. We can continue the parse even if except occurs.

Below is the stack trace.
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "next.children" is null
	at de.jplag.cpp2.CPPTokenListener.getDescendant(CPPTokenListener.java:375)
	at de.jplag.cpp2.CPPTokenListener.enterSimpleDeclaration(CPPTokenListener.java:326)
	at de.jplag.cpp2.grammar.CPP14Parser$SimpleDeclarationContext.enterRule(CPP14Parser.java:5639)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at de.jplag.cpp2.CPPParserAdapter.scan(CPPParserAdapter.java:46)
	at de.jplag.cpp2.CPPLanguage.parse(CPPLanguage.java:48)
	at de.jplag.Submission.parse(Submission.java:249)
	at de.jplag.SubmissionSet.parseSubmissions(SubmissionSet.java:147)
	at de.jplag.SubmissionSet.parseAllSubmissions(SubmissionSet.java:103)
	at de.jplag.SubmissionSet.<init>(SubmissionSet.java:45)
	at de.jplag.SubmissionSetBuilder.buildSubmissionSet(SubmissionSetBuilder.java:78)
	at de.jplag.JPlag.run(JPlag.java:55)
	at de.jplag.cli.CLI.main(CLI.java:91)
```

**Comment by tsaglam** [comment]
Closed by #1480.
