### ISSUE TITLE
`mvn clean generate-sources assembly:assembly` fails to build

### ISSUE THREAD

**Issue by sebastinas** [jplag/jplag#18]
When trying to build jplag with `mvn clean generate-sources assembly:assembly` as described in the `README.md` it fails with the following error:

```
[INFO] Reactor Summary:
[INFO] 
[INFO] JPlag Plagiarism Detector .......................... SUCCESS [  0.065 s]
[INFO] frontend-utils ..................................... SUCCESS [  0.007 s]
[INFO] chars .............................................. SUCCESS [  0.004 s]
[INFO] cpp ................................................ SUCCESS [  0.361 s]
[INFO] csharp-1.2 ......................................... SUCCESS [  0.342 s]
[INFO] java-1.1exp ........................................ SUCCESS [  0.248 s]
[INFO] java-1.2 ........................................... SUCCESS [  0.434 s]
[INFO] java-1.5 ........................................... SUCCESS [  0.387 s]
[INFO] java-1.7 ........................................... SUCCESS [  1.152 s]
[INFO] scheme ............................................. SUCCESS [  0.435 s]
[INFO] text ............................................... SUCCESS [  0.108 s]
[INFO] utils .............................................. SUCCESS [  0.004 s]
[INFO] jplag .............................................. SUCCESS [  0.594 s]
[INFO] JPlag Aggregator ................................... FAILURE [ 10.763 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.729 s
[INFO] Finished at: 2016-05-17T14:46:36+02:00
[INFO] Final Memory: 113M/710M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:assembly (default-cli) on project aggregator: Error reading assemblies: No assembly descriptors found. -> [Help 1]
```

When running `mvn` with `-e` it reports
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:assembly (default-cli) on project aggregator: Error reading assemblies: No assembly descriptors found. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:assembly (default-cli) on project aggregator: Error reading assemblies: No assembly descriptors found.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error reading assemblies: No assembly descriptors found.
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:356)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: org.apache.maven.plugin.assembly.io.AssemblyReadException: No assembly descriptors found.
        at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.readAssemblies(DefaultAssemblyReader.java:206)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:352)
        ... 22 more
```

**Comment by erikmd** [comment]
Maybe you forgot to do `cd jplag` before running `mvn clean generate-sources assembly:assembly` ?

**Comment by sebastinas** [comment]
I did. Sorry for the noise.
