### ISSUE TITLE
I can’t create or run fresh JPlag version

### ISSUE THREAD

**Issue by Mazdaywik** [jplag/jplag#19]
# Running partially fail
I want use latest version (master), but not release v2.11.8-SNAPSHOT because it have errors in C++ parser.

I cloned repository and run:
```
mvn clean generate-sources package
```

I ran it:
```
java -jar jplag/jplag/target/jplag-2.11.8-SNAPSHOT.jar -l c/c++ .
```

but got
```
Exception in thread "main" java.lang.NoClassDefFoundError: jplag/Language
        at jplag.JPlag.main(JPlag.java:12)
Caused by: java.lang.ClassNotFoundException: jplag.Language
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
```

# Creating single file fail:
```
[~/work/Plagiarism/JPlag/jplag/jplag] branch:master$ mvn assembly:assembly
/usr/java/jdk1.8.0_92/bin/..
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building jplag 2.11.8-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-assembly-plugin:2.4:assembly (default-cli) @ jplag >>>
Downloading: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/parent/0.3-SNAPSHOT/maven-metadata.xml
Downloaded: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/parent/0.3-SNAPSHOT/maven-metadata.xml (596 B at 2.0 KB/sec)
Downloading: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/parent/0.3-SNAPSHOT/parent-0.3-20150330.082632-3.pom
…
many other lines skipped
…
Downloading: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/cpp/0.0.2-SNAPSHOT/maven-metadata.xml
Downloaded: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/cpp/0.0.2-SNAPSHOT/maven-metadata.xml (770 B at 5.7 KB/sec)
Downloading: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/cpp/0.0.2-SNAPSHOT/cpp-0.0.2-20150330.082634-1.pom
Downloaded: http://bob.ipd.kit.edu/nexus/content/repositories/public/edu/kit/ipd/jplag/cpp/0.0.2-SNAPSHOT/cpp-0.0.2-20150330.082634-1.pom (3 KB at 23.3 KB/sec)
…
many other lines skipped
…
```

It download to folder `~/.m2/repository/edu/kit/ipd/jplag/` old (for release v2.11.8-SNAPSHOT) files and creates JAR with buggy C++ parser.

I’m newbie in maven, help me run or create ‘master’ version!

**Comment by NoctuaNivalis** [comment]
I've just started to use jplag, but I think it's because just building that jar doesn't include the dependencies. You should also `cd jplag`, followed by a `mvn clean generate-sources assembly:assembly`. You can then use the `i/don/t/know/where/you/saved/this/jplag/jplag/target/jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar` as a single runnable jar.
