### ISSUE TITLE
I am not able to run JPlag

### ISSUE THREAD

**Issue by fin-fyp** [jplag/jplag#45]
I want to run the version v2.11.9-SNAPSHOT..

I ran..
mvn clean generate-sources package in the base directory, followed by mvn clean generate-sources assembly:assembly inside the jplag directory.

Build was succesfull..
And The Jars were created in the respected target directories.

When I ran the Jar generated in the jplag/target, am getting the below error..

 java -jar jplag-2.11.9-SNAPSHOT.jar 

I got...

Exception in thread "main" java.lang.NoClassDefFoundError: jplag/ProgramI
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at jplag.options.Options.usage(Options.java:182)
	at jplag.JPlag.main(JPlag.java:9)
Caused by: java.lang.ClassNotFoundException: jplag.ProgramI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

When I specify  the language, am getting the below error..

java -jar jplag-2.11.9-SNAPSHOT.jar -l java17

I got..

Exception in thread "main" java.lang.NoClassDefFoundError: jplag/Language
	at jplag.JPlag.main(JPlag.java:12)
Caused by: java.lang.ClassNotFoundException: jplag.Language
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

I am newbie in maven, help me run this!

**Comment by PHCCorso** [comment]
Same here. The .jar files are generated and I had the same output as yours while trying to execute JPlag, but when running `mvn clean generate-sources assembly:assembly` I had this error, too:

```
[INFO] Reactor Summary:
[INFO] 
[INFO] JPlag Plagiarism Detector ......................... SUCCESS [0.101s]
[INFO] frontend-utils .................................... SUCCESS [0.006s]
[INFO] chars ............................................. SUCCESS [0.004s]
[INFO] cpp ............................................... SUCCESS [0.477s]
[INFO] csharp-1.2 ........................................ SUCCESS [0.399s]
[INFO] java-1.1exp ....................................... SUCCESS [0.362s]
[INFO] java-1.2 .......................................... SUCCESS [0.328s]
[INFO] java-1.5 .......................................... SUCCESS [0.406s]
[INFO] java-1.7 .......................................... SUCCESS [1.474s]
[INFO] python-3 .......................................... SUCCESS [0.525s]
[INFO] scheme ............................................ SUCCESS [0.305s]
[INFO] text .............................................. SUCCESS [0.172s]
[INFO] utils ............................................. SUCCESS [0.005s]
[INFO] jplag ............................................. SUCCESS [0.120s]
[INFO] JPlag Aggregator .................................. FAILURE [22.138s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.311s
[INFO] Finished at: Sat Dec 09 20:06:28 BRST 2017
[INFO] Final Memory: 81M/397M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:assembly (default-cli) on project aggregator: Error reading assemblies: No assembly descriptors found. -> [Help 1]
```

**Comment by seemar** [comment]
From https://github.com/jplag/jplag/issues/18, try cd jplag, and then running the above

**Comment by ngrash** [comment]
I had the same issue. Just running `mvn clean generate-sources assembly:assembly` as the README suggests results in an error:

```
[ERROR] Failed to execute goal on project csharp-1.2: Could not resolve dependencies for project edu.kit.ipd.jplag:csharp-1.2:jar:0.0.1-SNAPSHOT: Could not find artifact edu.kit.ipd.jplag:frontend-utils:jar:0.0.3-SNAPSHOT in ipdNexus (http://bob.ipd.kit.edu/nexus/content/repositories/public/)
```

I was able to run `java -jar jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar` (inside `jplag/target`) after doing what lama0206 suggested in https://github.com/jplag/jplag/issues/57#issuecomment-430123448:

```
$ mvn clean generate-sources install
$ mvn assembly:assembly
```

`mvn install` seems necessary to avoid hitting the artifacts repository which appears to have disappeared.
