### ISSUE TITLE
Full JDK instead of only JRE needed when comparing Java files

### ISSUE THREAD

**Issue by b-fein** [jplag/JPlag#845]
Related issues: #689, https://github.com/ls1intum/Artemis/issues/5945

Error when running inside an `docker.io/library/eclipse-temurin:17-jre` container:
```
root@b7ea47b9422a:/jplag_data# java -jar jplag-4.1.0-jar-with-dependencies.jar submissions/
2022-12-12-04:01:46_569 [main] [INFO] LanguageLoader - Available languages: '[C/C++ Scanner [basic markup], C# 6 Parser, EMF metamodel, Go Parser, Javac based AST plugin, Kotlin Parser, Python3 Parser, R Parser, Rust Language Module, Scala parser, SchemeR4RS Parser [basic markup], Swift Parser, Text Parser (naive)]'
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/source/tree/TreeVisitor
        at de.jplag.java.Parser.parse(Parser.java:25)
        at de.jplag.java.Language.parse(Language.java:47)
        at de.jplag.Submission.parse(Submission.java:249)
        at de.jplag.SubmissionSet.parseSubmissions(SubmissionSet.java:147)
        at de.jplag.SubmissionSet.parseAllSubmissions(SubmissionSet.java:103)
        at de.jplag.SubmissionSet.<init>(SubmissionSet.java:45)
        at de.jplag.SubmissionSetBuilder.buildSubmissionSet(SubmissionSetBuilder.java:78)
        at de.jplag.JPlag.run(JPlag.java:43)
        at de.jplag.cli.CLI.main(CLI.java:90)
Caused by: java.lang.ClassNotFoundException: com.sun.source.tree.TreeVisitor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more
```

The TreeVisitor class seems to be part of only the JDK https://docs.oracle.com/en/java/javase/17/docs/api/jdk.compiler/com/sun/source/tree/TreeVisitor.html (part of the [jdk.compiler](https://docs.oracle.com/en/java/javase/17/docs/api/jdk.compiler/module-summary.html) module), and is not bundled in the JRE.

I guess this is not a big issue in most cases, since I’d expect people interested in comparing Java files also have got the Java compiler installed.
However, when JPlag is used as a dependency from another application this might be more problematic: When packaging the application inside a Docker container we usually want to keep the container size small and therefore only package the JRE instead of the full JDK.

**Comment by tsaglam** [comment]
If JPlag is used as a dependency, the languages can be included individually (on Maven Central, JPlag is supplied via multiple jars). Thus, a JRE is enough as long as the Java language is not used as a dependency. Nonetheless, a JDK is required when using the Java language, as we use the JavaC API to parse and tokenize Java code. Thus, we consider this issue as closed.
